version: "3.8"
services:

  icinga:
    build:
      context: ./image-files
      dockerfile: Dockerfile
    environment:
      - CN=
      - ZONE=
      - PARENTHOST=
      - PARENTCN=
      - PARENTZONE=
      - TICKET=
